### ISSUE TITLE
Using toner without an engine

### ISSUE THREAD

**Issue by smehrbrodt** [jsreport/toner#2]
Is it possible to use toner without an engine (pass simple html)?

**Comment by pofider** [comment]
``` js
toner.engine("none", toner.noneEngine);
```

Is this enough?

**Comment by smehrbrodt** [comment]
Looks good. However, I get the following error: `Error: Engine 'none' not found"`

``` javascript
toner().engine('none', toner.noneEngine);
toner().render({
  template: {
    engine: 'none',
    recipe: recipe,
    content: result
  }
}, function(err, out) {
  out.result.pipe(res);
});
```

**Comment by pofider** [comment]
You seems to be creating toner instance twice. Do it just once and keep the instance.

``` js
var toner = require("toner")();
toner.engine(..);
toner.render(...);
```

**Comment by smehrbrodt** [comment]
That was the problem, thanks for your help!
And many thanks for the great software, it makes creating reports a breeze :)
