### ISSUE TITLE
Example of using toner with hapi.js?

### ISSUE THREAD

**Issue by dlong500** [jsreport/toner#3]
Does anyone have experience with using hapi and jsreport?  I'm trying to convert the basic toner examples to use hapi's architecture but not sure if I'm doing anything improperly.  The below example works but I don't know if there are any "gotchas" that would hurt performance or anything else.

``` javascript
    var toner = require("toner")();
    toner.engine("jsrender", require("toner-jsrender"));
    toner.recipe("wkhtmltopdf", require("toner-wkhtmltopdf")());

    var pdftest = function (request, reply) {  
      toner.render({
          template: { 
              engine: "jsrender",
              recipe: "wkhtmltopdf", 
              content: "<h1>{{:foo}}</h1>"
          },
          data: { foo: "hello world2"}
      }, function(err, res) {
          var pdfbuffer = res.content;
          var pdfstream = res.stream;
          reply(pdfstream);
      });
    };

    server.route([
      {
        method: 'GET',
        path: '/pdftest',
        config: {
          auth: 'session',
          handler: pdftest
        }
      }
    ]);
```

**Comment by pofider** [comment]
Hi,

I have no experience using hapi. I can just note this looks OK for toner.

**Comment by dlong500** [comment]
I'll close for now, but if you (or anyone else) comes across some hapi.js expert who is using jsreport I'd love to see some example code of how they are using it.
